add an action to add new issues and PRs to project
RMI-PACTA/pacta.portfolio.import pull request #32
Opened 2022-12-19 21:08 UTC by cjyetman

2023-01-16 11:28 UTC, AlexAxthelm approved these changes

2023-01-18 13:40 UTC, jdhoffa commented
I guess this should eventually get the same treatment as https://github.com/RMI-PACTA/pacta.data.preparation/pull/248 and friends re: using a generalized PAT

2023-01-18 13:45 UTC, cjyetman commented
Yup. Just need the org level PAT with appropriate permissions to be created.

2023-01-19 09:04 UTC, AlexAxthelm commented
I'll work  on setting that up

2023-02-13 15:34 UTC, AlexAxthelm requested changes

2023-02-13 15:34 UTC, AlexAxthelm commented on .github/workflows/add-prs-and-issues-to-project.yml
> +          github-token: ${{ secrets.CJ_ADD_TO_PROJECT_PAT }}
```suggestion
          github-token: ${{ secrets.PAT_ADD_ISSUES_TO_PROJECT }}
```

I've created the @PACTA-bot user who created the PAT_ADD_ISSUES_TO_PROJECT PAT with repo and project scopes.

2023-02-13 15:42 UTC, AlexAxthelm approved these changes

2023-02-13 15:55 UTC, merged